#------------------------------------------------------------
# common
#------------------------------------------------------------

pg: &pg
  adapter:  postgresql
  host:     localhost
  port:     5432
  encoding: utf8
  template: template0



#------------------------------------------------------------
# environments
#------------------------------------------------------------

development:
  <<: *pg
  host:     localhost
  username: dbuser
  password: dbuser
  database: rule_of_3_development


test:
  <<: *pg
  username: dbuser
  password: dbuser
  database: rule_of_3_test

production:
  <<: *pg
  username: dbuser
  password: dbuser
  database: rule_of_3_production
